name: Deploy API to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare jar file
        run: mv target/*.jar ./app.jar

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "app.jar,Dockerfile"
          target: "/opt/pharmacy-api"

      - name: Docker Build and Run
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /opt/pharmacy-api
            sudo docker build -t pharmacy-api-image .
            sudo docker rm -f pharmacy-api-container || true
            sudo docker run -d -p 8080:8080 --network pharmacy-net --name pharmacy-api-container --restart unless-stopped pharmacy-api-image
            sudo docker image prune -f